# Generated by Django 5.2.5 on 2025-08-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='topic',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
