# Generated by Django 5.2.5 on 2025-09-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_response"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="only_logged_in",
        ),
    ]
